nav:
  Home: /
  Archive: /archives/
  Category: /categories/
  # About: /about/
  # Writing: /posts/
  # Projects: http://github.com/urangurang

projects_url: http://github.com/urangurang

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/urangurang
        facebook: https://www.facebook.com/ddwax
        linkedin: https://www.linkedin.com/in/park-jinsoo-b0a6456a/
    show_all_posts: true
    post_count: 20
    highlight: railscasts

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: urangurang
    google_analytics: UA-158081532-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
